// CompareContainer Reducer
export const SET_COMPARE_CONTAINER = 'SET_COMPARE_CONTAINER'
export const SET_COMPARE_CONTAINER_TABLE = 'SET_COMPARE_CONTAINER_TABLE'
export const COMPARE_CONTAINER_FETCH = 'COMPARE_CONTAINER_FETCH'
export const SET_COMPARE_CONTAINER_TOTAL = 'SET_COMPARE_CONTAINER_TOTAL'
export const SET_COMPARE_CONTAINER_LIMIT = 'SET_COMPARE_CONTAINER_LIMIT'
export const SET_COMPARE_CONTAINER_SKIP = 'SET_COMPARE_CONTAINER_SKIP'
export const SET_COMPARE_CONTAINER_DATA = 'SET_COMPARE_CONTAINER_DATA'
export const OPEN_COMPARE_CONTAINER_DIALOG = 'OPEN_COMPARE_CONTAINER_DIALOG'
