// PartProdRate Reducer
export const PART_PROD_RATE_FETCH = 'PART_PROD_RATE_FETCH'
export const SET_PART_PROD_RATE_START_PERIOD = 'SET_PART_PROD_RATE_START_PERIOD'
export const SET_PART_PROD_RATE_END_PERIOD = 'SET_PART_PROD_RATE_END_PERIOD'
export const SET_PART_PROD_RATE_TOTAL = 'SET_PART_PROD_RATE_TOTAL'
export const SET_PART_PROD_RATE_LIMIT = 'SET_PART_PROD_RATE_LIMIT'
export const SET_PART_PROD_RATE_SKIP = 'SET_PART_PROD_RATE_SKIP'
export const SET_PART_PROD_RATE_DATA = 'SET_PART_PROD_RATE_DATA'
