// User Reducer
export const AUTHENTICATE_SAGA = 'AUTHENTICATE_SAGA'
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED'
export const SET_IS_ADMIN = 'SET_IS_ADMIN'
export const SET_FIRSTNAME = 'SET_FIRSTNAME'
export const SET_LASTNAME = 'SET_LASTNAME'
export const SET_USERNAME = 'SET_USERNAME'
export const SET_EMAIL = 'SET_EMAIL'
export const SET_ROLES = 'SET_ROLES'
export const REAUTHENTICATE = 'REAUTHENTICATE'
export const LOGOUT = 'LOGOUT'

